"""Versioned TV command-parser corpus. Synthetic phrases only; not private transcripts."""

from __future__ import annotations

from typing import Any, NamedTuple


class CorpusCase(NamedTuple):
    phrase: str
    decision: str
    category: str
    reason: str
    fallback: bool
    action: str | None = None
    args: dict[str, Any] | None = None
    parsed_kind: str = "command"
    candidates: int = 0


YOUTUBE_ID = "aqz-KE-bpKQ"

CASES: tuple[CorpusCase, ...] = (
    CorpusCase("pause", "match", "documented", "MATCH_TRANSPORT", False, "pause"),
    CorpusCase("pause !", "match", "documented", "MATCH_TRANSPORT", False, "pause"),
    CorpusCase("Pause", "match", "documented", "MATCH_TRANSPORT", False, "pause"),
    CorpusCase("  PAUSE  ", "match", "documented", "MATCH_TRANSPORT", False, "pause"),
    CorpusCase("mets en pause", "match", "documented", "MATCH_TRANSPORT", False, "pause"),
    CorpusCase("pause s'il te plaît", "match", "documented", "MATCH_TRANSPORT", False, "pause"),
    CorpusCase("reprends", "match", "documented", "MATCH_TRANSPORT", False, "resume"),
    CorpusCase("continue", "match", "documented", "MATCH_TRANSPORT", False, "resume"),
    CorpusCase("arrête", "match", "documented", "MATCH_TRANSPORT", False, "stop"),
    CorpusCase("arrete", "match", "documented", "MATCH_TRANSPORT", False, "stop"),
    CorpusCase("stop", "match", "documented", "MATCH_TRANSPORT", False, "stop"),
    CorpusCase("suivante", "match", "documented", "MATCH_PLAYLIST_NEXT", False, "playlist_next"),
    CorpusCase("suivante !", "match", "documented", "MATCH_PLAYLIST_NEXT", False, "playlist_next"),
    CorpusCase(
        "morceau suivant", "match", "documented", "MATCH_PLAYLIST_NEXT", False, "playlist_next"
    ),
    CorpusCase(
        "passe au suivant", "match", "documented", "MATCH_PLAYLIST_NEXT", False, "playlist_next"
    ),
    CorpusCase(
        "mets la playlist numéro 1",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 0},
    ),
    CorpusCase(
        "mets la playliste numéro 1",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 0},
    ),
    CorpusCase(
        "playlist une",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 0},
    ),
    CorpusCase(
        "première playlist",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 0},
    ),
    CorpusCase(
        "mets la première playlist",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 0},
    ),
    CorpusCase(
        "playlist deux",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 1},
    ),
    CorpusCase(
        "deuxième playlist",
        "match",
        "documented",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 1},
    ),
    CorpusCase(
        "avance de 30 secondes",
        "match",
        "documented",
        "MATCH_SEEK",
        False,
        "seek",
        {"delta_ms": 30_000},
    ),
    CorpusCase(
        "recule de 2 minutes",
        "match",
        "documented",
        "MATCH_SEEK",
        False,
        "seek",
        {"delta_ms": -120_000},
    ),
    CorpusCase(
        "avance de cinq secondes",
        "match",
        "documented",
        "MATCH_SEEK",
        False,
        "seek",
        {"delta_ms": 5_000},
    ),
    CorpusCase(
        "lance interstellar",
        "match",
        "documented",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "interstellar", "limit": 5},
    ),
    CorpusCase(
        "joue la video aqz-KE-bpKQ",
        "match",
        "documented",
        "MATCH_YOUTUBE",
        False,
        "play_content",
        {"content": {"kind": "youtube_video", "id": YOUTUBE_ID}},
    ),
    CorpusCase(
        "je mette Petunia de Werenoi sur la télé",
        "match",
        "documented",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "petunia de werenoi", "limit": 5},
    ),
    CorpusCase(
        "mets-moi Petunia de Werenoi sur SmartTube",
        "match",
        "documented",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "petunia de werenoi", "limit": 5},
    ),
    CorpusCase(
        "trouve Petunia de Werenoi sur YouTube",
        "match",
        "documented",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "petunia de werenoi", "limit": 5},
    ),
    CorpusCase(
        "je veux regarder Petunia de Werenoi sur SmartTube",
        "match",
        "documented",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "petunia de werenoi", "limit": 5},
    ),
    CorpusCase(
        "peux-tu lancer Petunia de Werenoi sur ma TV",
        "match",
        "documented",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "petunia de werenoi", "limit": 5},
    ),
    CorpusCase("ne mets pas en pause", "reject", "negation", "REJECT_NEGATION", False),
    CorpusCase("mets pas en pause", "reject", "negation", "REJECT_NEGATION", False),
    CorpusCase("n'arrête pas", "reject", "negation", "REJECT_NEGATION", False),
    CorpusCase("n’arrête pas", "reject", "negation", "REJECT_NEGATION", False),
    CorpusCase("ne lance pas Interstellar", "reject", "negation", "REJECT_NEGATION", False),
    CorpusCase(
        "je ne veux pas que tu lances la playlist une",
        "reject",
        "negation",
        "REJECT_NEGATION",
        False,
    ),
    CorpusCase("ne passe pas au suivant", "reject", "negation", "REJECT_NEGATION", False),
    CorpusCase(
        "ne mets pas en pause s'il te plaît",
        "reject",
        "negation",
        "REJECT_NEGATION",
        False,
    ),
    CorpusCase("je fais une pause", "reject", "not_command", "REJECT_NOT_COMMAND", False),
    CorpusCase("elle a dit pause", "reject", "not_command", "REJECT_NOT_COMMAND", False),
    CorpusCase("la semaine suivante", "reject", "not_command", "REJECT_NOT_COMMAND", False),
    CorpusCase(
        "j'ai vu le deuxième épisode",
        "reject",
        "not_command",
        "REJECT_NOT_COMMAND",
        False,
    ),
    CorpusCase("mets la table", "reject", "not_command", "REJECT_NOT_COMMAND", False),
    CorpusCase("arrête de parler", "reject", "not_command", "REJECT_NOT_COMMAND", False),
    CorpusCase("je faisais une pause", "reject", "not_command", "REJECT_NOT_COMMAND", False),
    CorpusCase(
        "joue Ne me quitte pas sur YouTube",
        "match",
        "title_collision",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "ne me quitte pas", "limit": 5},
    ),
    CorpusCase(
        "cherche Stop sur YouTube",
        "match",
        "title_collision",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "stop", "limit": 5},
    ),
    CorpusCase(
        "cherche Pause sur YouTube",
        "match",
        "title_collision",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "pause", "limit": 5},
    ),
    CorpusCase(
        "cherche Dune 2 sur YouTube",
        "match",
        "title_collision",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "dune 2", "limit": 5},
        "command",
        3,
    ),
    CorpusCase(
        'cherche le titre "Playlist" sur YouTube',
        "match",
        "title_collision",
        "MATCH_SEARCH",
        False,
        "search",
        {"query": "titre playlist", "limit": 5},
    ),
    CorpusCase(
        "premier",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "première",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "deuxième",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "deuxieme",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "second",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "seconde",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "troisième",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase(
        "troisieme",
        "match",
        "ordinal",
        "MATCH_PICK",
        False,
        None,
        None,
        "pick",
        3,
    ),
    CorpusCase("2", "match", "ordinal", "MATCH_PICK", False, None, None, "pick", 3),
    CorpusCase("2 !", "match", "ordinal", "MATCH_PICK", False, None, None, "pick", 3),
    CorpusCase(
        "premier",
        "ambiguous",
        "ordinal",
        "AMBIGUOUS_NO_CANDIDATES",
        False,
        None,
        None,
        "command",
        0,
    ),
    CorpusCase(
        "3",
        "ambiguous",
        "ordinal",
        "AMBIGUOUS_OUT_OF_RANGE",
        False,
        None,
        None,
        "command",
        2,
    ),
    CorpusCase(
        "mets la playlist",
        "ambiguous",
        "playlist",
        "AMBIGUOUS_PLAYLIST_INDEX",
        False,
    ),
    CorpusCase("playlist 0", "reject", "playlist", "REJECT_PLAYLIST_INDEX", False),
    CorpusCase(
        "playlist 999999",
        "match",
        "playlist",
        "MATCH_PLAYLIST",
        False,
        "playlist_play",
        {"index": 999998},
    ),
    CorpusCase("avance de -30 secondes", "reject", "seek", "REJECT_INVALID_SEEK", False),
    CorpusCase("pause puis reprends", "ambiguous", "multi", "AMBIGUOUS_MULTI_ACTION", False),
    CorpusCase("arrête puis pause", "ambiguous", "multi", "AMBIGUOUS_MULTI_ACTION", False),
    CorpusCase(
        "cette chanson à la télé s'il te plaît",
        "no_match",
        "fallback",
        "NO_MATCH",
        True,
    ),
    CorpusCase("queen", "no_match", "invalid", "NO_MATCH", False),
    CorpusCase("bonjour tout le monde", "no_match", "invalid", "NO_MATCH", False),
    CorpusCase("", "reject", "invalid", "REJECT_EMPTY", False),
    CorpusCase("   ", "reject", "invalid", "REJECT_EMPTY", False),
    CorpusCase("x" * 501, "reject", "invalid", "REJECT_TOO_LONG", False),
    CorpusCase(
        "joue la video AbC_De-fgH1",
        "match",
        "youtube_id",
        "MATCH_YOUTUBE",
        False,
        "play_content",
        {"content": {"kind": "youtube_video", "id": "AbC_De-fgH1"}},
    ),
)

ORDINAL_INDEX = {
    "premier": 0,
    "première": 0,
    "deuxième": 1,
    "deuxieme": 1,
    "second": 1,
    "seconde": 1,
    "troisième": 2,
    "troisieme": 2,
    "2": 1,
    "2 !": 1,
}
